<?php


/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function cilb_user_management_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // alter the password reset form for non-logged in users
  if ($form_id === 'user_pass' && !\Drupal::currentUser()->isAuthenticated()) {
    // add SSN field
    $form['dob'] = \Drupal\cilb_user_management\Form\Utils::getDobField();

    // ensure ssn field appears before help text (which is confusingly keyed as 'mail')
    $form['dob']['#weight'] = 10;
    $form['mail']['#weight'] = 20;

    // update the label on email/username form to be email specifically
    $form['name']['#title'] = t('Registered email address');

    // add our custom validator
    $form['#validate'][] = 'cilb_user_management_user_pass_form_validate';
  }
}

function cilb_user_management_user_pass_form_validate($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $dob = $form_state->getValue('dob');
  $submittedEmail = $form_state->getValue('name');

  \Drupal::service('civicrm')->initialize();

  $matchingContact = \Civi\Api4\Contact::get(FALSE)
    ->addSelect('id')
    ->addWhere('email_primary.email', '=', $submittedEmail)
    ->addWhere('birth_date', '=', $dob)
    ->addWhere('is_deleted', '=', FALSE)
    ->execute()
    ->first();

  if (!$matchingContact) {
    $form_state->setErrorByName('dob', t('No contact record found with these details.'));
    return;
  }

  $matchingUser = \Civi\Api4\UFMatch::get(FALSE)
    ->addWhere('contact_id', '=', $matchingContact['id'])
    ->execute()
    ->first();

  if (!$matchingUser) {
    $form_state->setErrorByName('dob', t('No user account exists for these details. Please <a href="/user/activate">activate your account</a> to continue.'));
    return;
  }

  $user = \Drupal\user\Entity\User::load($matchingUser['uf_id']);

  if ($user->getEmail() !== $submittedEmail) {
    $form_state->setErrorByName('name', t('This is not the email we have on record for your account.'));
    return;
  }
  $form_state->setValueForElement(['#parents' => ['account']], $user);

}
