<?php
use CRM_Cilb_Import_ExtensionUtil as E;
return [
  [
    'name' => 'CustomGroup_Registrant_Info',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Registrant_Info',
        'extends' => 'Individual',
        'collapse_display' => TRUE,
        'weight' => 3,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-07-22 10:35:32',
        'title' => E::ts('Registrant Info'),
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Registrant_Info_CustomField_SSN',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Registrant_Info',
        'name' => 'SSN',
        'label' => E::ts('Social Security Number'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ssn_5',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Registrant_Info_CustomField_Degree_in_Building_Construction',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Registrant_Info',
        'name' => 'Degree_in_Building_Construction',
        'label' => E::ts('Degree in Building Construction'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'degree_in_building_construction_2',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Registrant_Info_Exam_Language_Preference',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Registrant_Info_Exam_Language_Preference',
        'title' => E::ts('Registrant Info :: Exam Language Preference'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Registrant_Info_Exam_Language_Preference_OptionValue_English',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Registrant_Info_Exam_Language_Preference',
        'label' => E::ts('English'),
        'value' => '1',
        'name' => 'English',
        'description' => '',
        'Exam_Part_Options.Category_Specific' => NULL,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Registrant_Info_Exam_Language_Preference_OptionValue_Spanish',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Registrant_Info_Exam_Language_Preference',
        'label' => E::ts('Español'),
        'value' => '2',
        'name' => 'Spanish',
        'description' => '',
        'Exam_Part_Options.Category_Specific' => NULL,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Registrant_Info_CustomField_Exam_Language_Preference',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Registrant_Info',
        'name' => 'Exam_Language_Preference',
        'label' => E::ts('Exam Language Preference'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'exam_language_preference_3',
        'option_group_id.name' => 'Registrant_Info_Exam_Language_Preference',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Registrant_Info_CustomField_ADA_Accommodations_Needed',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Registrant_Info',
        'name' => 'ADA_Accommodations_Needed',
        'label' => E::ts('ADA Accommodations Needed'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ada_accommodations_needed_4',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Registrant_Info_CustomField_Candidate_Representative_Name',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Registrant_Info',
        'name' => 'Candidate_Representative_Name',
        'label' => E::ts('Candidate Representative Name'),
        'html_type' => 'Text',
        'is_active' => FALSE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'candidate_representative_name_7',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Registrant_Info_CustomField_Restriction_Reason',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Registrant_Info',
        'name' => 'Restriction_Reason',
        'label' => E::ts('Restriction Reason'),
        'html_type' => 'Text',
        'column_name' => 'restriction_reason_15',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Registrant_Info_CustomField_Is_Restricted',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Registrant_Info',
        'name' => 'Is_Restricted',
        'label' => E::ts('Is Restricted?'),
        'data_type' => 'Boolean',
        'html_type' => 'CheckBox',
        'column_name' => 'is_restricted__16',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
