<?php
use CRM_CilbReports_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Exam_Registrations_by_Application_Transaction_Date',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Exam_Registrations_by_Application_Transaction_Date',
        'label' => E::ts('Exam Registrations by Application Transaction Date'),
        'api_entity' => 'Participant',
        'api_params' => [
          'version' => 4,
          'select' => [
            'GROUP_FIRST(Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01.receive_date) AS GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_receive_date',
            'GROUP_FIRST(Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01.trxn_id) AS GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_trxn_id',
            'GROUP_FIRST(Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01.id) AS GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_id',
            'contact_id.sort_name',
            'Participant_Contact_contact_id_01.Registrant_Info.SSN',
            'GROUP_FIRST(Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01.payment_instrument_id:label) AS GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_payment_instrument_id_label',
            'GROUP_FIRST(Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01.check_number) AS GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_check_number',
            'SUM(Participant_LineItem_entity_id_01.line_total) AS SUM_Participant_LineItem_entity_id_01_line_total',
            'SUM(Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_Contribution_EntityFinancialTrxn_FinancialTrxn_01.amount) AS SUM_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_Contribution_EntityFinancialTrxn_FinancialTrxn_01_amount',
            'GROUP_FIRST(Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01.total_amount) AS GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_total_amount',
            'id',
            'Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01_LocBlock_Address_address_id_01.street_address',
            'Participant_Event_event_id_01.start_date',
            'event_id.title',
            'source',
            'Participant_Event_event_id_01.event_type_id:label',
            'Participant_Contact_contact_id_01.Registrant_Info.Candidate_Representative_Name',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [
            'id',
            'Participant_Event_event_id_01.id',
            'Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01_LocBlock_Address_address_id_01.id',
            'Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01.id',
            'Participant_Contact_contact_id_01.id',
          ],
          'join' => [
            [
              'Event AS Participant_Event_event_id_01',
              'INNER',
              [
                'event_id',
                '=',
                'Participant_Event_event_id_01.id',
              ],
            ],
            [
              'LineItem AS Participant_LineItem_entity_id_01',
              'INNER',
              [
                'id',
                '=',
                'Participant_LineItem_entity_id_01.entity_id',
              ],
              [
                'Participant_LineItem_entity_id_01.entity_table',
                '=',
                '\'civicrm_participant\'',
              ],
            ],
            [
              'LocBlock AS Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01',
              'LEFT',
              [
                'Participant_Event_event_id_01.loc_block_id',
                '=',
                'Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01.id',
              ],
            ],
            [
              'Address AS Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01_LocBlock_Address_address_id_01',
              'LEFT',
              [
                'Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01.address_id',
                '=',
                'Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01_LocBlock_Address_address_id_01.id',
              ],
              [
                'Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01_LocBlock_Address_address_id_01.is_primary',
                '=',
                TRUE,
              ],
            ],
            [
              'Contact AS Participant_Contact_contact_id_01',
              'LEFT',
              [
                'contact_id',
                '=',
                'Participant_Contact_contact_id_01.id',
              ],
            ],
            [
              'Contribution AS Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01',
              'INNER',
              [
                'Participant_LineItem_entity_id_01.contribution_id',
                '=',
                'Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01.id',
              ],
            ],
            [
              'FinancialTrxn AS Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_Contribution_EntityFinancialTrxn_FinancialTrxn_01',
              'LEFT',
              'EntityFinancialTrxn',
              [
                'Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01.id',
                '=',
                'Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_Contribution_EntityFinancialTrxn_FinancialTrxn_01.entity_id',
              ],
              [
                'Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_Contribution_EntityFinancialTrxn_FinancialTrxn_01.entity_table',
                '=',
                '\'civicrm_contribution\'',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Exam_Registrations_by_Application_Transaction_Date_SearchDisplay_Exam_Registrations_by_Application_Transaction_Date',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Exam_Registrations_by_Application_Transaction_Date',
        'label' => E::ts('Exam Registrations by Application Transaction Date'),
        'saved_search_id.name' => 'Exam_Registrations_by_Application_Transaction_Date',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(NULL),
          'sort' => [
            [
              'GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_receive_date',
              'ASC',
            ],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_receive_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Trans Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_id',
              'dataType' => 'Integer',
              'label' => E::ts('Payment#'),
              'sortable' => TRUE,
              'link' => [
                'path' => 'civicrm/contact/view/contribution?reset=1&id=[Participant_LineItem_entity_id_01.contribution_id]&action=view',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => '',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_trxn_id',
              'dataType' => 'String',
              'label' => E::ts('Trans#'),
              'sortable' => TRUE,
              'empty_value' => '-',
            ],
            [
              'type' => 'field',
              'key' => 'contact_id.sort_name',
              'dataType' => 'String',
              'label' => E::ts('Applicant Name'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'contact_id',
                'target' => '',
              ],
              'title' => E::ts('View Contact'),
              'rewrite' => '',
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contact_contact_id_01.Registrant_Info.SSN',
              'dataType' => 'String',
              'label' => E::ts('SSN'),
              'sortable' => TRUE,
              'rewrite' => 'XXX-XX-{"[Participant_Contact_contact_id_01.Registrant_Info.SSN]"|substr:-4}',
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_payment_instrument_id_label',
              'dataType' => 'Integer',
              'label' => E::ts('Payment Method'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_check_number',
              'dataType' => 'String',
              'label' => E::ts('Check#'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_FIRST_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_total_amount',
              'dataType' => 'Money',
              'label' => E::ts('Total To Pay'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'SUM_Participant_LineItem_entity_id_01_line_total',
              'dataType' => 'Money',
              'label' => E::ts('Seat Fee'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'SUM_Participant_LineItem_entity_id_01_LineItem_Contribution_contribution_id_01_Contribution_EntityFinancialTrxn_FinancialTrxn_01_amount',
              'dataType' => 'Money',
              'label' => E::ts('Amount Paid'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('Cand#'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Event_event_id_01_Event_LocBlock_loc_block_id_01_LocBlock_Address_address_id_01.street_address',
              'dataType' => 'String',
              'label' => E::ts('Test Site'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Event_event_id_01.start_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Exam Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Event_event_id_01.event_type_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Category'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'event_id.title',
              'dataType' => 'String',
              'label' => E::ts('Exam Parts'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'source',
              'dataType' => 'String',
              'label' => E::ts('Created By'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contact_contact_id_01.Registrant_Info.Candidate_Representative_Name',
              'dataType' => 'String',
              'label' => E::ts('Created By'),
              'sortable' => TRUE,
              'rewrite' => '{if "[Participant_Contact_contact_id_01.Registrant_Info.Candidate_Representative_Name]"}[Participant_Contact_contact_id_01.Registrant_Info.Candidate_Representative_Name]{else}[contact_id.sort_name]{/if}',
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
