<?php
use CRM_CilbReports_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Find_Candidates',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Find_Candidates',
        'label' => E::ts('Find Candidates'),
        'api_entity' => 'Participant',
        'api_params' => [
          'version' => 4,
          'select' => [
            'contact_id.sort_name',
            'event_id.title',
            'Participant_Contribution_Candidate_Payment_01.trxn_id',
            'fee_level',
            'Participant_Contribution_Candidate_Payment_01.total_amount',
            'register_date',
            'status_id:label',
            'role_id:label',
            'Candidate_Result.Date_Exam_Taken',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [
            [
              'Contribution AS Participant_Contribution_Candidate_Payment_01',
              'LEFT',
              [
                'Participant_Webform.Candidate_Payment',
                '=',
                'Participant_Contribution_Candidate_Payment_01.id',
              ],
            ],
            [
              'Event AS Participant_Event_event_id_01',
              'INNER',
              [
                'event_id',
                '=',
                'Participant_Event_event_id_01.id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Find_Candidates_SearchDisplay_Find_Candidates',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Find_Candidates',
        'label' => E::ts('Find Candidates'),
        'saved_search_id.name' => 'Find_Candidates',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(NULL),
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'contact_id.sort_name',
              'dataType' => 'String',
              'label' => E::ts('Candidate'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'event_id.title',
              'dataType' => 'String',
              'label' => E::ts('Exam'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contribution_Candidate_Payment_01.trxn_id',
              'dataType' => 'String',
              'label' => E::ts('Transaction ID'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'fee_level',
              'dataType' => 'Text',
              'label' => E::ts('Fee Level'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'register_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Registered'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Candidate_Result.Date_Exam_Taken',
              'dataType' => 'Date',
              'label' => E::ts('Date Exam Taken'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Status'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'role_id:label',
              'dataType' => 'String',
              'label' => E::ts('Role'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => 'Participant',
                  'action' => 'view',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('View Candidate'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'Participant',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Update Candidate'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'Participant',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete Candidate'),
                  'style' => 'danger',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-center',
              'label' => E::ts('Actions'),
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
          'button' => NULL,
          'toolbar' => [
            [
              'entity' => '',
              'text' => E::ts('Backoffice Registration'),
              'icon' => 'fa-external-link',
              'target' => '_blank',
              'action' => '',
              'style' => 'default',
              'join' => '',
              'path' => 'form/backoffice-registration',
              'task' => '',
              'conditions' => [],
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
