<?php

use Drupal\webform\Utility\WebformFormHelper;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\block\Entity\Block;
use Drupal\cilb_candidate_registration\Plugin\WebformHandler\CilbCandidateRegistrationWebformHandler;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Menu\MenuLinkInterface;

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function cilb_candidate_registration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (
    $form_id == "webform_submission_register_english_add_form"
    || $form_id == "webform_submission_backoffice_registration_add_form"
  ) {
    if ($form_id == 'webform_submission_register_english_add_form' && isset($form['actions']['reset'])) {
      $form['actions']['reset']['#value'] = t('Cancel');
      $form['actions']['reset']['#attributes']['class'][] = 'btn-danger';
    }
    if ($form_id == "webform_submission_register_english_add_form") {
      // Redirect to /register if notification block is disabled
      $elements = WebformFormHelper::flattenElements($form);
      $original_markup = $elements['user_identification_markup']['#markup'];

      if (!_is_block_active('bootstrap_barrio_subtheme_candidatenotice')) {
        $updated_markup = preg_replace(
          '/https:\/\/cilb\.jmaconsulting\.biz\/(es\/)?register-notification/',
          'https://www.floridaexam.com/register',
          $original_markup
        );
        $updated_markup = preg_replace(
          '/https:\/\/www\.floridaexam\.com\/(es\/)?register-notification/',
          'https://www.floridaexam.com/register',
          $original_markup
        );
        $elements['user_identification_markup']['#markup'] = $updated_markup;
      }
    }
  }
}

function cilb_candidate_registration_preprocess_page(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface && $node->id() == 6) {
    $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $block_id = 'bootstrap_barrio_subtheme_candidatenotice';

    // Redirect to webform if notification block is disabled
    if (!_is_block_active($block_id)) {
      if ($current_language == 'es') {
        $redirect_url = Url::fromUri('internal:/es/exam-registration');
      } else {
        $redirect_url = Url::fromUri('internal:/exam-registration');
      }
      $response = new RedirectResponse($redirect_url->toString());
      $response->send();
      exit();
    }
  }
}

function _is_block_active($block_id) {
  $block = Block::load($block_id);
  return $block && $block->status();
}

/**
 * Implements hook_views_query_alter().
 */
function cilb_candidate_registration_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'exam_type' && $view->current_display == 'entity_reference_1') {

    // Check to make sure exams types are not full
    $events = \Civi\Api4\Event::get(FALSE)
      ->addSelect('option_value.id')
      ->addJoin('OptionValue AS option_value', 'LEFT', ['event_type_id', '=', 'option_value.value'])
      ->addWhere('is_active', '=', TRUE)
      //  ->addWhere('start_date', '>', 'now')
      //   ->addWhere('is_online_registration', '=', TRUE)
      ->addClause('OR', ['max_participants', 'IS NULL'], ['remaining_participants', '>', 0])
      ->addWhere('option_value.option_group_id', '=', 15)
      ->addGroupBy('event_type_id')
      ->addGroupBy('option_value.id')
      ->execute();

    $valid_option_ids = [];
    foreach ($events as $event) {
      $valid_option_ids[] = $event['option_value.id'];
    }

    if (!empty($valid_option_ids)) {
      $query->addWhere('AND', 'civicrm_option_value.id', $valid_option_ids, 'IN');
    } else {
      $query->addWhere('AND', 'civicrm_option_value.id', '0', '=');
    }
  }
}

function cilb_candidate_registration_token_info() {
  $info = [];
  $info['contribution-id'] = [
    'name' => t('Webform CiviCRM Contribution ID'),
    'description' => t('The ID of Contribution that got created after submitting the webform. Replace the "?" with the contribution number starting from 1'),
    'dynamic' => TRUE,
  ];

  return ['tokens' => ['webform_submission' => $info]];
}

function cilb_candidate_registration_tokens($type, $tokens = '', array $data = [], array $options = []) {
  if (!($type === 'webform_submission' && !empty($data['webform_submission']))) {
    return;
  }
  $contributionId = \Drupal::service('webform_civicrm.postprocess')->getContributionId() ?? $data['webform_submission']->getData()['civicrm']['contribution'][1]['id'];
  if ($contributionId) {
    return ['[webform_submission:contribution-id:1]' => $contributionId];
  }
}

/**
 * Implements hook_preprocess_HOOK() for menu.html.twig.
 */
function cilb_candidate_registration_preprocess_menu(&$variables) {
  $current_user = \Drupal::currentUser();
  if ($current_user->hasRole('staff') && $variables['menu_name'] == 'main') {  // 'main' = your menu name
    foreach ($variables['items'] as &$item) {
      if ($item['title'] == 'Home' || $item['url']->getInternalPath() == '<front>') {
        $item['url'] = \Drupal\Core\Url::fromUri('internal:/admin/config/cilb-admin-dashboard');
        break;
      }
    }
  }
}
