<?php

use CRM_AdvancedEvents_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Event_Templates',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Event_Templates',
        'label' => E::ts('Event Templates'),
        'api_entity' => 'Event',
        'api_params' => [
          'version' => 4,
          'select' => [
            'template_title',
            'title',
            'event_type_id:label',
            'created_id',
            'financial_type_id:label',
            'summary',
            'start_date',
            'end_date',
            'is_public',
            'is_monetary',
            'is_online_registration',
            'is_active',
            'COUNT(Event_EventTemplate_template_id_01.event_id) AS COUNT_Event_EventTemplate_template_id_01_event_id',
          ],
          'orderBy' => [],
          'where' => [
            [
              'is_template',
              '=',
              TRUE,
            ],
          ],
          'groupBy' => [
            'id',
          ],
          'join' => [
            [
              'EventTemplate AS Event_EventTemplate_template_id_01',
              'LEFT',
              [
                'id',
                '=',
                'Event_EventTemplate_template_id_01.template_id',
              ],
            ],
            [
              'EventTemplate AS Event_EventTemplate_event_id_01',
              'LEFT',
              [
                'id',
                '=',
                'Event_EventTemplate_event_id_01.event_id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Event_Templates_SearchDisplay_Event_Templates_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Event_Templates_Table_1',
        'label' => E::ts('Event Templates Table 1'),
        'saved_search_id.name' => 'Event_Templates',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'template_title',
              'dataType' => 'String',
              'label' => E::ts('Title'),
              'sortable' => TRUE,
              'link' => [
                'path' => 'civicrm/event/manage/settings?action=update&reset=1&id=[id]',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => '',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'event_type_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Type'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'created_id',
              'dataType' => 'Integer',
              'label' => E::ts('Created By'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'created_id',
                'target' => '_blank',
              ],
              'title' => E::ts('View Created By'),
            ],
            [
              'type' => 'field',
              'key' => 'financial_type_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Financial Type'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'summary',
              'dataType' => 'Text',
              'label' => E::ts('Summary'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Start Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('End Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_public',
              'dataType' => 'Boolean',
              'label' => E::ts('Public'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_monetary',
              'dataType' => 'Boolean',
              'label' => E::ts('Paid Event'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_online_registration',
              'dataType' => 'Boolean',
              'label' => E::ts('Online Registration'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'COUNT_Event_EventTemplate_template_id_01_event_id',
              'dataType' => 'Integer',
              'label' => E::ts('Events'),
              'sortable' => TRUE,
              'link' => [
                'path' => 'civicrm/event/manage/settings?action=update&reset=1&selectedChild=linkedevents&id=[id]',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => '_blank',
              ],
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'icon' => 'fa-calendar-plus-o',
                  'text' => E::ts('Create Event'),
                  'style' => 'default',
                  'path' => 'civicrm/event/add?reset=1&action=add&template_id=[id]',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'path' => 'civicrm/event/manage/settings?action=update&reset=1&id=[id]',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Edit'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'Event',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-off',
                  'text' => E::ts('Disable'),
                  'style' => 'default',
                  'path' => '',
                  'task' => 'disable',
                  'condition' => [
                    'is_active',
                    '=',
                    TRUE,
                  ],
                ],
                [
                  'task' => 'enable',
                  'entity' => 'Event',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-on',
                  'text' => E::ts('Enable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [
                    'is_active',
                    '=',
                    FALSE,
                  ],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'Event',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'condition' => [],
                ],
                [
                  'path' => 'civicrm/admin/eventTemplate/copy?id=[id]',
                  'icon' => 'fa-clone',
                  'text' => E::ts('Copy'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => [
            'event.copyparticipant',
            'download',
            'delete',
          ],
          'classes' => [
            'table',
            'table-striped',
          ],
          'cssRules' => [
            [
              'disabled',
              'is_active',
              '=',
              FALSE,
            ],
          ],
          'headerCount' => TRUE,
          'toolbar' => [
            [
              'action' => '',
              'entity' => '',
              'text' => E::ts('Add New Template'),
              'icon' => 'fa-calendar-plus-o',
              'style' => 'default',
              'target' => 'crm-popup',
              'join' => '',
              'path' => 'civicrm/event/add?action=add&reset=1&is_template=1',
              'task' => '',
              'condition' => [],
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
