<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from advimport/xml/schema/CRM/Advimport/Advimport.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:3b57183bc739ca96114906ed40e1f7e3)
 */
use CRM_Advimport_ExtensionUtil as E;

/**
 * Database access object for the Advimport entity.
 */
class CRM_Advimport_DAO_Advimport extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_advimport';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Advimport ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Contact, import author
   *
   * @var int
   */
  public $contact_id;

  /**
   * Mapping helper class name
   *
   * @var string
   */
  public $classname;

  /**
   * Import start
   *
   * @var timestamp
   */
  public $start_date;

  /**
   * Import end
   *
   * @var timestamp
   */
  public $end_date;

  /**
   * Name of the file uploaded
   *
   * @var string
   */
  public $filename;

  /**
   * SQL table where the data is staged before being processed
   *
   * @var string
   */
  public $table_name;

  /**
   * Total number of rows
   *
   * @var int
   */
  public $total_count;

  /**
   * Number of rows imported successful
   *
   * @var int
   */
  public $success_count;

  /**
   * Number of rows imported with warnings
   *
   * @var int
   */
  public $warning_count;

  /**
   * Number of rows that failed to import because of errors
   *
   * @var int
   */
  public $error_count;

  /**
   * Ex: group or tag used to track contacts imported
   *
   * @var string
   */
  public $track_entity_type;

  /**
   * ID of the group or tag used to track contacts imported
   *
   * @var int
   */
  public $track_entity_id;

  /**
   * Field mapping
   *
   * @var text
   */
  public $mapping;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_advimport';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Advimports') : E::ts('Advimport');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Advimport ID'),
          'required' => TRUE,
          'where' => 'civicrm_advimport.id',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact'),
          'description' => E::ts('FK to Contact, import author'),
          'where' => 'civicrm_advimport.contact_id',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => '1.0',
        ],
        'classname' => [
          'name' => 'classname',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Class Name'),
          'description' => E::ts('Mapping helper class name'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_advimport.classname',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'start_date' => [
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Start Date'),
          'description' => E::ts('Import start'),
          'where' => 'civicrm_advimport.start_date',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'end_date' => [
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('End Date'),
          'description' => E::ts('Import end'),
          'where' => 'civicrm_advimport.end_date',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'filename' => [
          'name' => 'filename',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Filename'),
          'description' => E::ts('Name of the file uploaded'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_advimport.filename',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'table_name' => [
          'name' => 'table_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Table Name'),
          'description' => E::ts('SQL table where the data is staged before being processed'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_advimport.table_name',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'total_count' => [
          'name' => 'total_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Total Count'),
          'description' => E::ts('Total number of rows'),
          'where' => 'civicrm_advimport.total_count',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'success_count' => [
          'name' => 'success_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Success Count'),
          'description' => E::ts('Number of rows imported successful'),
          'where' => 'civicrm_advimport.success_count',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'warning_count' => [
          'name' => 'warning_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Warning Count'),
          'description' => E::ts('Number of rows imported with warnings'),
          'where' => 'civicrm_advimport.warning_count',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'error_count' => [
          'name' => 'error_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Error Count'),
          'description' => E::ts('Number of rows that failed to import because of errors'),
          'where' => 'civicrm_advimport.error_count',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'track_entity_type' => [
          'name' => 'track_entity_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Track Entity Type'),
          'description' => E::ts('Ex: group or tag used to track contacts imported'),
          'maxlength' => 128,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_advimport.track_entity_type',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'track_entity_id' => [
          'name' => 'track_entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Track Entity ID'),
          'description' => E::ts('ID of the group or tag used to track contacts imported'),
          'where' => 'civicrm_advimport.track_entity_id',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
        'mapping' => [
          'name' => 'mapping',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Mapping'),
          'description' => E::ts('Field mapping'),
          'where' => 'civicrm_advimport.mapping',
          'table_name' => 'civicrm_advimport',
          'entity' => 'Advimport',
          'bao' => 'CRM_Advimport_DAO_Advimport',
          'localizable' => 0,
          'add' => '1.0',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'advimport', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'advimport', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
